using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraBars;
using System.ComponentModel.DataAnnotations;
using MySql.Data.MySqlClient;
using System.Data.Common;
using System.Runtime.CompilerServices; 

namespace QLCafeWinform
{
    public partial class QLBan : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public int mamon = 0;

        public QLBan()
        {
            InitializeComponent();       
           

           
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }
        void bbiPrintPreview_ItemClick(object sender, ItemClickEventArgs e)
        {

        }

        private void bbiNew_ItemClick(object sender, ItemClickEventArgs e)
        {
            frmthemSP them = new frmthemSP();
            them.Show();
            this.Hide();
        }

       

        private void bbiEdit_ItemClick(object sender, ItemClickEventArgs e)
        {
            string ma = gridViewSP.GetFocusedDisplayText();
            
            MySqlConnection conn = getDB.getData();
            conn.Open();
            string sql = "select MaMon from thucdon where MaMon=" + ma;
            string mamon = "";
            try
            {
                
                MySqlCommand cmd = new MySqlCommand();
                cmd.Connection = conn;
                cmd.CommandText = sql;

                using (DbDataReader reader = cmd.ExecuteReader())
                {
                    if (reader.HasRows)
                    {
                        while (reader.Read())
                        {
                            int idindex = reader.GetOrdinal("MaMon");
                            string ML = reader.GetString(idindex);
                            mamon = ML;
                        }
                    }
                }
                if (mamon != "")
                {
                    frmSuasp sua = new frmSuasp(mamon);
                    sua.Show();
                    this.Hide();
                }
                else
                {
                    MessageBox.Show("Mời chọn vào ô mã món", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                    return;
                }
            }
            catch
            {
                MessageBox.Show("Mời chọn vào ô mã món", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            }
            finally
            {
                conn.Close();
                conn.Dispose();
            }
        }

        private void bbiDelete_ItemClick(object sender, ItemClickEventArgs e)
        {
            string mamon = gridViewSP.GetFocusedDisplayText();
            DialogResult r;
            r=MessageBox.Show("Bạn có muốn xóa?", "xóa thông tin", MessageBoxButtons.YesNo, MessageBoxIcon.Warning);
            if (r == DialogResult.Yes)
            {
                MySqlConnection conn = getDB.getData();
                conn.Open();
                string sql = "delete from thucdon where mamon =" + mamon;
                try
                {
                    MySqlCommand cmd = new MySqlCommand(sql, conn);
                    if (cmd.ExecuteNonQuery() == 1)
                    {
                        MessageBox.Show("Thành công", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    }
                    else
                    {
                        MessageBox.Show("Fails", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }

                    this.Hide();
                    QLBan ban = new QLBan();
                    ban.Show();
                }
                catch
                {
                    MessageBox.Show("Mời chọn vào ô mã món", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                }
                finally
                {
                    conn.Close();
                    conn.Dispose();
                }
            }
            
            
        }

        private void bbiRefresh_ItemClick(object sender, ItemClickEventArgs e)
        {
            this.Hide();
            QLBan ban = new QLBan();
            ban.Show();           
            
        }

        private void QLBan_Load(object sender, EventArgs e)
        {
            
        }

        private void barButtonItem4_ItemClick(object sender, ItemClickEventArgs e)
        {
            
        }
       
    }
}