using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraBars;
using MySql.Data.MySqlClient;
using System.Data.Common;


namespace QLCafeWinform
{
    public partial class QLChucVu : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public QLChucVu()
        {
            InitializeComponent();



            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }
        void bbiPrintPreview_ItemClick(object sender, ItemClickEventArgs e)
        {
        }
       
        private void bbiRefresh_ItemClick(object sender, ItemClickEventArgs e)
        {
            QLChucVu cv = new QLChucVu();
            this.Hide();
            cv.Show();
        }

        private void bbiNew_ItemClick(object sender, ItemClickEventArgs e)
        {
            frmthemcv cv = new frmthemcv();
            this.Hide();
            cv.Show();

        }

        private void bbiEdit_ItemClick(object sender, ItemClickEventArgs e)
        {
            string ma = gridViewCV.GetFocusedDisplayText();

            MySqlConnection conn = getDB.getData();
            conn.Open();
            string sql = "select * from chucvu where MaCV = '"+ ma +"'";
            string macv = "";
            try
            {

                MySqlCommand cmd = new MySqlCommand();
                cmd.Connection = conn;
                cmd.CommandText = sql;

                using (DbDataReader reader = cmd.ExecuteReader())
                {
                    if (reader.HasRows)
                    {
                        while (reader.Read())
                        {
                            int idindex = reader.GetOrdinal("MaCV");
                            string ML = reader.GetString(idindex);
                            macv = ML;
                        }
                    }
                }
                if (macv != "")
                {
                    frmSuaCV sua = new frmSuaCV(macv);
                    sua.Show();
                    this.Hide();
                }
                else
                {
                    MessageBox.Show("Mời chọn vào ô mã chức vụ", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                    return;
                }
            }
            catch
            {
                MessageBox.Show("Mời chọn vào ô mã chức vụ", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            }
            finally
            {
                conn.Close();
                conn.Dispose();
            }
        }

        private void barButtonItem1_ItemClick(object sender, ItemClickEventArgs e)
        {
           
        }
    }
}